name: CI

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      FEEDZ_PROXYKIT_API_KEY: ${{secrets.FEEDZ_PROXYKIT_API_KEY}}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Test
      run: bash build.sh
      shell: bash